--Config type 0: click and type integer (type, value/default, indicator, label, min, max) --Type used by quantity
--Config type 1: click on 5-point liner selector (type, selected/default 1-5, indicator, label, 5 options)
--Config type 2: toggle switch (type, text, boolean/default, label)
--Config type 3: click buttons to increment integer (type, value/default, label, step)

--If quantity is editable {0, "10", "#:", "Quantity", 1, 1000} must be first config
--6 configs max per item
--config type 0 does not support negative values currently

--(label, unit price, is quantity editable, config arrays)--
--Quantity editable example {"Acacia Boat", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {3, 0, "Config-C", 1, -10, 10}} --Quantity is the first config slot
--Quantity not editable example {"Acacia Boat", 10, false, {0, "-25", "&:", "ConfigD", -50, 50}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {3, 0, "Config-C", 1, -10, 10}}  --Quantity is locked at 1 and configD is first config slot
itemList = {
    {"Acacia Boat", 10, false},
    {"Acacia Boat with Chest", 10, false, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}},
    {"Amethyst Shard", 10, false, {2, false, "Config B"}},
    {"Angler Pottery Sherd", 10, false, {3, 0, "Config-C", 1, -10, 10}},
    {"Apple", 10, false, {0, "25", "&:", "ConfigD", 0, 50}},
    {"Archer Pottery Sherd", 10, false, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}},
    {"Armor Stand", 10, false, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}},
    {"Arms Up Pottery Sherd", 10, false, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}},
    {"Arrow", 10, false, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}},
    
    {"Baked Potato", 10, true, {0, "10", "#:", "Quantity", 1, 1000}},
    {"Bamboo Raft", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}},
    {"Bamboo Raft with Chest", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {2, false, "Config B"}},
    {"Banner Pattern (Creeper Charge)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {3, 0, "Config-C", 1, -10, 10}},
    {"Banner Pattern (Flower Charge)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {0, "25", "&:", "ConfigD", 0, 50}},
    {"Banner Pattern (Globe)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}, {1, 1, "%:", "ConfigA:", 0, 25, 50, 75, 100}},
    {"Banner Pattern (Skull Charge)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}, {2, false, "Config B"}},
    {"Banner Pattern (Snout)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}, {3, 0, "Config-C", 1, -10, 10}},
    {"Banner Pattern (Thing)", 10, true, {0, "10", "#:", "Quantity", 1, 1000}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", -50, 50}, {0, "25", "&:", "ConfigD", 0, 50}, {0, "25", "&:", "ConfigD", 0, 50}},

    {"Beetroot", 10, false}, --Extra to test search scroll
    {"Beetroot Seeds", 10, false},
    {"Beetroot Soup", 10, false},
    {"Birch Boat", 10, false},
    {"Birch Boat with Chest", 10, false},
    {"Black Dye", 10, false},
    {"Blade Pottery Sherd", 10, false},
    {"Blaze Powder", 10, false},
    {"Blaze Rod", 10, false},
    {"Blue Dye", 10, false},
    {"Bone", 10, false},
    {"Bone Meal", 10, false},
    {"Book", 10, false},
    {"Book and Quill", 10, false},
    {"Bottle o Enchanting", 10, false},
    {"Bow", 10, false},
    {"Bowl", 10, false},
    {"Bread", 10, false},
    {"Brewer Pottery Sherd", 10, false},
    {"Brick", 10, false},
    {"Brown Dye", 10, false},
    {"Brush", 10, false},
    {"Bucket", 10, false},
    {"Bucket of Axolotl", 10, false},
    {"Bucket of Cod", 10, false},
    {"Bucket of Pufferfish", 10, false},
    {"Bucket of Salmon", 10, false},
    {"Bucket of Tadpole", 10, false},
    {"Bucket of Tropical Fish", 10, false},
    {"Bundle", 10, false},
    {"Burn Pottery Sherd", 10, false}
}
    --[[{"Carrot", false},--Bad formatting, no unit price
    {"Carrot on a Stick", false},
    {"Chainmail Boots", false},
    {"Chainmail Chestplate", false},
    {"Chainmail Helmet", false},
    {"Chainmail Leggings", false},
    {"Charcoal", false},
    {"Cherry Boat", false},
    {"Cherry Boat with Chest", false},
    {"Chorus Fruit", false},
    {"Clay Ball", false},
    {"Clock", false},
    {"Coal", false},
    {"Coast Armor Trim", false},
    {"Cocoa Beans", false},
    {"Compass", false},
    {"Cooked Chicken", false},
    {"Cooked Cod", false},
    {"Cooked Mutton", false},
    {"Cooked Porkchop", false},
    {"Cooked Rabbit", false},
    {"Cooked Salmon", false},
    {"Cookie", false},
    {"Copper Ingot", false},
    {"Crossbow", false},
    {"Cyan Dye", false},
    {"Danger Pottery Sherd", false},
    {"Dark Oak Boat", false},
    {"Dark Oak Boat with Chest", false},
    {"Debug Stick[JE only]", false},
    {"Diamond", false},
    {"Diamond Axe", false},
    {"Diamond Boots", false},
    {"Diamond Chestplate", false},
    {"Diamond Helmet", false},
    {"Diamond Hoe", false},
    {"Diamond Horse Armor", false},
    {"Diamond Leggings", false},
    {"Diamond Pickaxe", false},
    {"Diamond Shovel", false},
    {"Diamond Sword", false},
    {"Disc Fragment", false},
    {"Dragons Breath", false},
    {"Dried Kelp", false},
    {"Dune Armor Trim", false},
    {"Echo Shard", false},
    {"Egg", false},
    {"Elytra", false},
    {"Emerald", false},
    {"Empty Map", false},
    {"Enchanted Book", false},
    {"Enchanted Golden Apple", false},
    {"End Crystal", false},
    {"Ender Pearl", false},
    {"Explorer Pottery Sherd", false},
    {"Eye Armor Trim", false},
    {"Eye of Ender", false},
    {"Feather", false},
    {"Fermented Spider Eye", false},
    {"Fire Charge", false},
    {"Firework Rocket", false},
    {"Firework Star", false},
    {"Fishing Rod", false},
    {"Flint", false},
    {"Flint and Steel", false},
    {"Friend Pottery Sherd", false},
    {"Ghast Tear", false},
    {"Glass Bottle", false},
    {"Glistering Melon Slice", false},
    {"Glow Berries", false},
    {"Glow Ink Sac", false},
    {"Glow Item Frame", false},
    {"Glowstone Dust", false},
    {"Goat Horn", false},
    {"Gold Ingot", false},
    {"Gold Nugget", false},
    {"Golden Apple", false},
    {"Golden Axe", false},
    {"Golden Boots", false},
    {"Golden Carrot", false},
    {"Golden Chestplate", false},
    {"Golden Helmet", false},
    {"Golden Hoe", false},
    {"Golden Horse Armor", false},
    {"Golden Leggings", false},
    {"Golden Pickaxe", false},
    {"Golden Shovel", false},
    {"Golden Sword", false},
    {"Gray Dye", false},
    {"Green Dye", false},
    {"Gunpowder", false},
    {"Heart Pottery Sherd", false},
    {"Heart of the Sea", false},
    {"Heartbreak Pottery Sherd", false},
    {"Honey Bottle", false},
    {"Honeycomb", false},
    {"Host Armor Trim", false},
    {"Howl Pottery Sherd", false},
    {"Ink Sac", false},
    {"Ink Sac", false},
    {"Iron Axe", false},
    {"Iron Boots", false},
    {"Iron Chestplate", false},
    {"Iron Helmet", false},
    {"Iron Hoe", false},
    {"Iron Horse Armor", false},
    {"Iron Ingot", false},
    {"Iron Ingot", false},
    {"Iron Leggings", false},
    {"Iron Nugget", false},
    {"Iron Pickaxe", false},
    {"Iron Shovel", false},
    {"Iron Sword", false},
    {"Item Frame", false},
    {"Jungle Boat", false},
    {"Jungle Boat with Chest", false},
    {"Kelp", false},
    {"Knowledge Book", false},
    {"Lapis Lazuli", false},
    {"Lapis Lazuli", false},
    {"Lava Bucket", false},
    {"Lead", false},
    {"Leather", false},
    {"Leather Boots", false},
    {"Leather Cap", false},
    {"Leather Horse Armor", false},
    {"Leather Pants", false},
    {"Leather Tunic", false},
    {"Light Blue Dye", false},
    {"Light Gray Dye", false},
    {"Lime Dye", false},
    {"Lingering Potion", false},
    {"Magenta Dye", false},
    {"Magma Cream", false},
    {"Mangrove Boat", false},
    {"Mangrove Boat with Chest", false},
    {"Map or Explorer Map", false},
    {"Melon Seeds", false},
    {"Melon Slice", false},
    {"Milk Bucket", false},
    {"Minecart", false},
    {"Minecart with Chest", false},
    {"Minecart with Command Block", false},
    {"Minecart with Furnace", false},
    {"Minecart with Hopper", false},
    {"Minecart with TNT", false},
    {"Miner Pottery Sherd", false},
    {"Mourner Pottery Sherd", false},
    {"Mushroom Stew", false},
    {"Music Disc (11)", false},
    {"Music Disc (13)", false},
    {"Music Disc (5)", false},
    {"Music Disc (Blocks)", false},
    {"Music Disc (Cat)", false},
    {"Music Disc (Chirp)", false},
    {"Music Disc (Far)", false},
    {"Music Disc (Mall)", false},
    {"Music Disc (Mellohi)", false},
    {"Music Disc (Otherside)", false},
    {"Music Disc (Pigstep)", false},
    {"Music Disc (Relic)", false},
    {"Music Disc (Stal)", false},
    {"Music Disc (Strad)", false},
    {"Music Disc (Wait)", false},
    {"Music Disc (Ward)", false},
    {"Name Tag", false},
    {"Nautilus Shell", false},
    {"Nether Brick", false},
    {"Nether Quartz", false},
    {"Nether Star", false},
    {"Nether Wart", false},
    {"Netherite Axe", false},
    {"Netherite Boots", false},
    {"Netherite Chestplate", false},
    {"Netherite Helmet", false},
    {"Netherite Hoe", false},
    {"Netherite Ingot", false},
    {"Netherite Leggings", false},
    {"Netherite Pickaxe", false},
    {"Netherite Scrap", false},
    {"Netherite Shovel", false},
    {"Netherite Sword", false},
    {"Netherite Upgrade", false},
    {"Oak Boat", false},
    {"Oak Boat with Chest", false},
    {"Orange Dye", false},
    {"Painting", false},
    {"Paper", false},
    {"Phantom Membrane", false},
    {"Pink Dye", false},
    {"Pitcher Pod", false},
    {"Plenty Pottery Sherd", false},
    {"Poisonous Potato", false},
    {"Popped Chorus Fruit", false},
    {"Potato", false},
    {"Potions", false},
    {"Powder Snow Bucket", false},
    {"Prismarine Crystals", false},
    {"Prismarine Shard", false},
    {"Prize Pottery Sherd", false},
    {"Pufferfish", false},
    {"Pumpkin Pie", false},
    {"Pumpkin Seeds", false},
    {"Purple Dye", false},
    {"Rabbit Hide", false},
    {"Rabbit Stew", false},
    {"Rabbits Foot", false},
    {"Raiser Armor Trim", false},
    {"Raw Beef", false},
    {"Raw Chicken", false},
    {"Raw Cod", false},
    {"Raw Copper", false},
    {"Raw Gold", false},
    {"Raw Iron", false},
    {"Raw Mutton", false},
    {"Raw Porkchop", false},
    {"Raw Rabbit", false},
    {"Raw Salmon", false},
    {"Recovery Compass", false},
    {"Red Dye", false},
    {"Redstone Dust", false},
    {"Rib Armor Trim", false},
    {"Rotten Flesh", false},
    {"Saddle", false},
    {"Scute", false},
    {"Sentry Armor Trim", false},
    {"Shaper Armor Trim", false},
    {"Sheaf Pottery Sherd", false},
    {"Shears", false},
    {"Shelter Pottery Sherd", false},
    {"Shield", false},
    {"Shulker Shell", false},
    {"Silence Armor Trim", false},
    {"Skull Pottery Sherd", false},
    {"Slimeball", false},
    {"Snort Pottery Sherd", false},
    {"Snowball", false},
    {"Spectral Arrow", false},
    {"Spider Eye", false},
    {"Spire Armor Trim", false},
    {"Splash Potion", false},
    {"Spruce Boat", false},
    {"Spruce Boat with Chest", false},
    {"Spyglass", false},
    {"Steak", false},
    {"Stick", false},
    {"Stone Axe", false},
    {"Stone Hoe", false},
    {"Stone Pickaxe", false},
    {"Stone Shovel", false},
    {"Stone Sword", false},
    {"String", false},
    {"Sugar", false},
    {"Suspicious Stew", false},
    {"Sweet Berries", false},
    {"Tide Armor Trim", false},
    {"Tipped Arrow", false},
    {"Torchflower Seeds", false},
    {"Totem of Undying", false},
    {"Trident", false},
    {"Tropical Fish", false},
    {"Turtle Shell", false},
    {"Vex Armor Trim", false},
    {"Ward Armor Trim", false},
    {"Warped Fungus on a Stick", false},
    {"Water Bucket", false},
    {"Wayfinder Armor Trim", false},
    {"Wheat", false},
    {"Wheat Seeds", false},
    {"White Dye", false},
    {"Wild Armor Trim", false},
    {"Wooden Axe", false},
    {"Wooden Hoe", false},
    {"Wooden Pickaxe", false},
    {"Wooden Shovel", false},
    {"Wooden Sword", false},
    {"Written Book", false},
    {"Yellow Dye", false}
}]]
